name: deploy_prod

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build-and-push-docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ vars.DOCKER_IMAGE_NAME }}:${{ github.ref_name }}

      - name: Comment on release with image info
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release comment ${{ github.ref_name }} \
            --body "🚀 Imagen de producción pushada a Docker Hub
          📦 \`${{ vars.DOCKER_IMAGE_NAME }}:${{ github.ref_name }}\`
